
import com.educrea.security.Role
import com.educrea.domain.Curso
import com.educrea.domain.Modulo
import com.educrea.domain.domicilio.Pais
import com.educrea.domain.domicilio.EntidadFederativa
import com.educrea.domain.domicilio.TipoAsentamiento
import com.educrea.security.User
import com.educrea.security.UserRole

class BootStrap {

    def init = { 
      //servletContext ->
      def suRole = new Role('ROLE_SU').save()
      
      def adminRole = new Role('ROLE_ADMIN').save()
      def userRole = new Role('ROLE_USER').save()

      def admin = new User('admin', 'admin').save()
      
      def instructor = new User('instructor', 'instructor').save()
      def alumno = new User('alumno', 'alumno').save()

      UserRole.create admin, adminRole
      UserRole.create admin, suRole
      UserRole.create instructor, adminRole
      UserRole.create alumno, userRole
        

    def tipoAsentamiento = new TipoAsentamiento('Colonia').save()
    def tipoAsentamiento2 = new TipoAsentamiento('Gran usuario').save()
    def tipoAsentamiento3 = new TipoAsentamiento('Pueblo').save()
    def tipoAsentamiento4 = new TipoAsentamiento('Unidad habitacional').save()
    def tipoAsentamiento5 = new TipoAsentamiento('Barrio').save()
    def tipoAsentamiento6 = new TipoAsentamiento('Condominio').save()
    def tipoAsentamiento7 = new TipoAsentamiento('Campamento').save()
    def tipoAsentamiento8 = new TipoAsentamiento('Fraccionamiento').save()
    def tipoAsentamiento9 = new TipoAsentamiento('Conjunto habitacional').save()
    def tipoAsentamiento10 = new TipoAsentamiento('Equipamiento').save()
    def tipoAsentamiento11 = new TipoAsentamiento('Residencial').save()
    def tipoAsentamiento12 = new TipoAsentamiento('Club de golf').save()
    def tipoAsentamiento13 = new TipoAsentamiento('Aeropuerto').save()
    def tipoAsentamiento14 = new TipoAsentamiento('Zona comercial').save()
    def tipoAsentamiento15 = new TipoAsentamiento('Ranchería').save()
    def tipoAsentamiento16 = new TipoAsentamiento('Parque industrial').save()
    def tipoAsentamiento17 = new TipoAsentamiento('Granja').save()
    def tipoAsentamiento18 = new TipoAsentamiento('Poblado comunal').save()
    def tipoAsentamiento19 = new TipoAsentamiento('Ejido').save()
    def tipoAsentamiento20 = new TipoAsentamiento('Congregación').save()
    def tipoAsentamiento21 = new TipoAsentamiento('Zona federal').save()
    def tipoAsentamiento22 = new TipoAsentamiento('Zona industrial').save()
    def tipoAsentamiento23 = new TipoAsentamiento('Hacienda').save()
    def tipoAsentamiento24 = new TipoAsentamiento('Estación').save()
    def tipoAsentamiento25 = new TipoAsentamiento('Ampliación').save()
    def tipoAsentamiento26 = new TipoAsentamiento('Puerto').save()
    def tipoAsentamiento27 = new TipoAsentamiento('Rancho').save()
    def tipoAsentamiento28 = new TipoAsentamiento('Ciudad').save()
    def tipoAsentamiento29 = new TipoAsentamiento('Ingenio').save()
    def tipoAsentamiento30= new TipoAsentamiento('Villa').save()
    def tipoAsentamiento31 = new TipoAsentamiento('Exhacienda').save()
    def tipoAsentamiento32 = new TipoAsentamiento('Paraje').save()
    def tipoAsentamiento33 = new TipoAsentamiento('Finca').save()
    def tipoAsentamiento34 = new TipoAsentamiento('Zona militar').save()
      
        
        def pais1 = new Pais('Afganistán', 'AF','AFG',93).save()
    def pais2 = new Pais('Albania', 'AL','ALB',355).save()
    def pais3 = new Pais('Alemania', 'DE','DEU',49).save()
    def pais4 = new Pais('Algeria', 'DZ','DZA',213).save()
    def pais5 = new Pais('Andorra', 'AD','AND',376).save()
    def pais6 = new Pais('Angola', 'AO','AGO',244).save()
    def pais7 = new Pais('Anguila', 'AI','AIA',1264).save()
    def pais8 = new Pais('Antártida', 'AQ','ATA',672).save()
    def pais9 = new Pais('Antigua y Barbuda', 'AG','ATG',1268).save()
    def pais10 = new Pais('Antillas Neerlandesas', 'AN','ANT',599).save()
    def pais11 = new Pais('Arabia Saudita', 'SA','SAU',966).save()
    def pais12 = new Pais('Argentina', 'AR','ARG',54).save()
    def pais13 = new Pais('Armenia', 'AM','ARM',374).save()
    def pais14 = new Pais('Aruba', 'AM','ABW',297).save()
    def pais15 = new Pais('Australia', 'AU','AUS',61).save()
    def pais16 = new Pais('Austria', 'AT','AUT',43).save()
    def pais17 = new Pais('Azerbayán', 'AZ','AZE',994).save()
    def pais18 = new Pais('Bélgica', 'BE','BEL',32).save()
    def pais19 = new Pais('Bahamas', 'BS','BHS',1242).save()
    def pais20 = new Pais('Bahrein', 'BH','BHR',973).save()
    def pais21 = new Pais('Bangladesh', 'BD','BGD',880).save()
    def pais22 = new Pais('Barbados', 'BB','BRB',1246).save()
    def pais23 = new Pais('Belice', 'BZ','BLZ',501).save()
    def pais24 = new Pais('Benín', 'BJ','BEN',229).save()
    def pais25 = new Pais('Bhután', 'BT','BTN',975).save()
    def pais26 = new Pais('Bielorrusia', 'BY','BLR',375).save()
    def pais27 = new Pais('Birmania', 'MM','MMR',95).save()
    def pais28 = new Pais('Bolivia', 'BO','BOL',591).save()
    def pais29 = new Pais('Bosnia y Herzegovina', 'BA','BIH',387).save()
    def pais30 = new Pais('Botsuana', 'BW','BWA',267).save()
    def pais31 = new Pais('Brasil', 'BR','BRA',55).save()
    def pais32 = new Pais('Brunéi', 'BN','BRN',673).save()
    def pais33 = new Pais('Bulgaria', 'BG','BGR',359).save()
    def pais34 = new Pais('Burkina Faso', 'BF','BFA',226).save()
    def pais35 = new Pais('Burundi', 'BI','BDI',257).save()
    def pais36 = new Pais('Cabo Verde', 'CV','CPV',238).save()
    def pais37 = new Pais('Camboya', 'KH','KHM',855).save()
    def pais38 = new Pais('Camerún', 'CM','CMR',237).save()
    def pais39 = new Pais('Canadá', 'CA','CAN',1).save()
    def pais40 = new Pais('Chad', 'TD','TCD',235).save()
    def pais41 = new Pais('Chile', 'CL','CHL',56).save()
    def pais42 = new Pais('China', 'CN','CHN',86).save()
    def pais43 = new Pais('Chipre', 'CY','CYP',357).save()
    def pais44 = new Pais('Ciudad del Vaticano', 'VA','VAT',39).save()
    def pais45 = new Pais('Colombia', 'CO','COL',57).save()
    def pais46 = new Pais('Comoras', 'KM','COM',269).save()
    def pais47 = new Pais('Congo', 'CG','COG',242).save()
    def pais48 = new Pais('Congo', 'CD','COD',243).save()
    def pais49 = new Pais('Corea del Norte', 'KP','PRK',850).save()
    def pais50 = new Pais('Corea del Sur', 'KR','KOR',82).save()
    def pais51 = new Pais('Costa de Marfil', 'CI','CIV',225).save()
    def pais52 = new Pais('Costa Rica', 'CR','CRI',506).save()
    def pais53 = new Pais('Croacia', 'HR','HRV',385).save()
    def pais54 = new Pais('Cuba', 'CU','CUB',53).save()
    def pais55 = new Pais('Dinamarca', 'DK','DNK',45).save()
    def pais56 = new Pais('Dominica', 'DM','DMA',1767).save()
    def pais57 = new Pais('Ecuador', 'EC','ECU',593).save()
    def pais58 = new Pais('Egipto', 'EG','EGY',20).save()
    def pais59 = new Pais('El Salvador', 'SV','SLV',503).save()
    def pais60 = new Pais('Emiratos Árabes Unidos', 'AE','ARE',971).save()
    def pais61 = new Pais('Eritrea', 'ER','ERI',291).save()
    def pais62 = new Pais('Eslovaquia', 'SK','SVK',421).save()
    def pais63 = new Pais('Eslovenia', 'SI','SVN',386).save()
    def pais64 = new Pais('España', 'ES','ESP',34).save()
    def pais65 = new Pais('Estados Unidos de América', 'US','USA',1).save()
    def pais66 = new Pais('Estonia', 'EE','EST',372).save()
    def pais67 = new Pais('Etiopía', 'ET','ETH',251).save()
    def pais68 = new Pais('Filipinas', 'PH','PHL',63).save()
    def pais69 = new Pais('Finlandia', 'FI','FIN',358).save()
    def pais70 = new Pais('Fiyi', 'FJ','FJI',679).save()
    def pais71 = new Pais('Francia', 'FR','FRA',33).save()
    def pais72 = new Pais('Gabón', 'GA','GAB',241).save()
    def pais73 = new Pais('Gambia', 'GM','GMB',220).save()
    def pais74 = new Pais('Georgia', 'GE','GEO',995).save()
    def pais75 = new Pais('Ghana', 'GH','GHA',233).save()
    def pais76 = new Pais('Gibraltar', 'GI','GIB',350).save()
    def pais77 = new Pais('Granada', 'GD','GRD',1473).save()
    def pais78 = new Pais('Grecia', 'GR','GRC',30).save()
    def pais79 = new Pais('Groenlandia', 'GL','GRL',299).save()
    
    def pais80 = new Pais('Guadalupe', 'GP','GLP',null).save()
    def pais81 = new Pais('Guam', 'GU','GUM',1671).save()
    def pais82 = new Pais('Guatemala', 'GT','GTM',502).save()
    def pais83 = new Pais('Guayana Francesa', 'GF','GUF',null).save()
    def pais84 = new Pais('Guernsey', 'GG','GGY',null).save()
    def pais85 = new Pais('Guinea', 'GN','GIN',224).save()
    def pais86 = new Pais('Guinea Ecuatorial', 'GQ','GNQ',240).save()
    def pais87 = new Pais('Guinea-Bissau', 'GW','GNB',245).save()
    def pais88 = new Pais('Guyana', 'GY','GUY',592).save()
    def pais89 = new Pais('Haití', 'HT','HTI',509).save()
    def pais90 = new Pais('Honduras', 'HN','HND',504).save()
    def pais91 = new Pais('Hong kong', 'HK','HKG',852).save()
    def pais92 = new Pais('Hungría', 'HU','HUN',36).save()
    def pais93 = new Pais('India', 'IN','IND',91).save()
    def pais94 = new Pais('Indonesia', 'ID','IDN',62).save()
    def pais95 = new Pais('Irán', 'IR','IRN',98).save()
    def pais96 = new Pais('Irak', 'IQ','IRQ',964).save()
    def pais97 = new Pais('Irlanda', 'IE','IRL',353).save()
    def pais98 = new Pais('Isla Bouvet', 'BV','BVT',null).save()
    def pais99 = new Pais('Isla de Man', 'IM','IMN',44).save()
    def pais100 = new Pais('Isla de Navidad', 'CX','CXR',61).save()
    def pais101 = new Pais('Isla Norfolk', 'NF','NFK',null).save()
    def pais102 = new Pais('Islandia', 'IS','ISL',354).save()
    def pais103 = new Pais('Islas Bermudas', 'BM','BMU',1441).save()
    def pais104 = new Pais('Islas Caimán', 'KY','CYM',1345).save()
    def pais105 = new Pais('Islas Cocos (Keeling)', 'CC','CCK',61).save()
    def pais106 = new Pais('Islas Cook', 'CK','COK',682).save()
    def pais107 = new Pais('Islas de Åland', 'AX','ALA',null).save()
    def pais108 = new Pais('Islas Feroe', 'FO','FRO',298).save()
    def pais109 = new Pais('Islas Georgias del Sur y Sandwich del Sur', 'GS','SGS',null).save()
    def pais110 = new Pais('Islas Heard y McDonald', 'HM','HMD',null).save()
    def pais111 = new Pais('Islas Maldivas', 'MV','MDV',960).save()
    def pais112 = new Pais('Islas Malvinas', 'FK','FLK',500).save()
    def pais113 = new Pais('Islas Marianas del Norte', 'MP','MNP',1670).save()
    def pais114 = new Pais('Islas Marshall', 'MH','MHL',692).save()
    def pais115 = new Pais('Islas Pitcairn', 'PN','PCN',870).save()
    def pais116 = new Pais('Islas Salomón', 'SB','SLB',677).save()
    def pais117 = new Pais('Islas Turcas y Caicos', 'TC','TCA',1649).save()
    def pais118 = new Pais('Islas Ultramarinas Menores de Estados Unidos', 'UM','UMI',null).save()
    def pais119 = new Pais('Islas Vírgenes Británicas', 'VG','VG',1284).save()
    def pais120 = new Pais('Islas Vírgenes de los Estados Unidos', 'VI','VIR',1340).save()
    def pais121 = new Pais('Israel', 'IL','ISR',972).save()
    def pais122 = new Pais('Italia', 'IT','ITA',39).save()
    def pais123 = new Pais('Jamaica', 'JM','JAM',1876).save()
    def pais124 = new Pais('Japón', 'JP','JPN',81).save()
    def pais125 = new Pais('Jersey', 'JE','JEY',null).save()
    def pais126 = new Pais('Jordania', 'JO','JOR',962).save()
    def pais127 = new Pais('Kazajistán', 'KZ','KAZ',7).save()
    def pais128 = new Pais('Kenia', 'KE','KEN',254).save()
    def pais129 = new Pais('Kirgizstán', 'KG','KGZ',996).save()
    def pais130 = new Pais('Kiribati', 'KI','KIR',686).save()
    def pais131 = new Pais('Kuwait', 'KW','KWT',965).save()
    def pais132 = new Pais('Líbano', 'LB','LBN',961).save()
    def pais133 = new Pais('Laos', 'LA','LAO',856).save()
    def pais134 = new Pais('Lesoto', 'LS','LSO',266).save()
    def pais135 = new Pais('Letonia', 'LV','LVA',371).save()
    def pais136 = new Pais('Liberia', 'LR','LBR',231).save()
    def pais137 = new Pais('Libia', 'LY','LBY',218).save()
    def pais138 = new Pais('Liechtenstein', 'LI','LIE',423).save()
    def pais139 = new Pais('Lituania', 'LT','LTU',370).save()
    def pais140 = new Pais('Luxemburgo', 'LU','LUX',352).save()
    def pais141 = new Pais('México', 'MX','MEX',52).save()
    def pais142 = new Pais('Mónaco', 'MC','MCO',377).save()
    def pais143 = new Pais('Macao', 'MO','MAC',853).save()
    def pais144 = new Pais('Macedônia', 'MK','MKD',389).save()
    def pais145 = new Pais('Madagascar', 'MG','MDG',261).save()
    def pais146 = new Pais('Malasia', 'MY','MYS',60).save()
    def pais147 = new Pais('Malawi', 'MW','MWI',265).save()
    def pais148 = new Pais('Mali', 'ML','MLI',223).save()
    def pais149 = new Pais('Malta', 'MT','MLT',356).save()
    def pais150 = new Pais('Marruecos', 'MA','MAR',212).save()
    def pais151 = new Pais('Martinica', 'MQ','MTQ',null).save()
    def pais152 = new Pais('Mauricio', 'MU','MUS',230).save()
    def pais153 = new Pais('Mauritania', 'MR','MRT',222).save()
    def pais154 = new Pais('Mayotte', 'YT','MYT',262).save()
    def pais155 = new Pais('Micronesia', 'FM','FSM',691).save()
    def pais156 = new Pais('Moldavia', 'MD','MDA',373).save()
    def pais157 = new Pais('Mongolia', 'MN','MNG',976).save()
    def pais158 = new Pais('Montenegro', 'ME','MNE',382).save()
    def pais159 = new Pais('Montserrat', 'MS','MSR',1664).save()
    def pais160 = new Pais('Mozambique', 'MZ','MOZ',258).save()
    def pais161 = new Pais('Namibia', 'NA','NAM',264).save()
    def pais162 = new Pais('Nauru', 'NR','NRU',674).save()
    def pais163 = new Pais('Nepal', 'NP','NPL',977).save()
    def pais164 = new Pais('Nicaragua', 'NI','NIC',505).save()
    def pais165 = new Pais('Niger', 'NE','NER',227).save()
    def pais166 = new Pais('Nigeria', 'NG','NGA',234).save()
    def pais167 = new Pais('Niue', 'NU','NIU',683).save()
    def pais168 = new Pais('Noruega', 'NO','NOR',47).save()
    def pais169 = new Pais('Nueva Caledonia', 'NC','NCL',687).save()
    def pais170 = new Pais('Nueva Zelanda', 'NZ','NZL',64).save()
    def pais171 = new Pais('Omán', 'OM','OMN',968).save()
    def pais172 = new Pais('Países Bajos', 'NL','NLD',31).save()
    def pais173 = new Pais('Pakistán', 'PK','PAK',92).save()
    def pais174 = new Pais('Palau', 'PW','PLW',680).save()
    def pais175 = new Pais('Palestina', 'PS','PSE',null).save()
    def pais176 = new Pais('Panamá', 'PA','PAN',507).save()
    def pais177 = new Pais('Papúa Nueva Guinea', 'PG','PNG',675).save()
    def pais178 = new Pais('Paraguay', 'PY','PRY',595).save()
    def pais179 = new Pais('Perú', 'PE','PER',51).save()
    def pais180 = new Pais('Polinesia Francesa', 'PF','PYF',689).save()
    def pais181 = new Pais('Polonia', 'PL','POL',48).save()
    def pais182 = new Pais('Portugal', 'PT','PRT',351).save()
    def pais183 = new Pais('Puerto Rico', 'PR','PRI',1).save()
    def pais184 = new Pais('Qatar', 'QA','QAT',974).save()
    def pais185 = new Pais('Reino Unido', 'GB','GBR',44).save()
    def pais186 = new Pais('República Centroafricana', 'CF','CAF',236).save()
    def pais187 = new Pais('República Checa', 'CZ','CZE',420).save()
    def pais188 = new Pais('República Dominicana', 'DO','DOM',1809).save()
    def pais189 = new Pais('Reunión', 'RE','REU',null).save()
    def pais190 = new Pais('Ruanda', 'RW','RWA',250).save()
    def pais191 = new Pais('Rumanía', 'RO','ROU',40).save()
    def pais192 = new Pais('Rusia', 'RU','RUS',7).save()
    def pais193 = new Pais('Sahara Occidental', 'EH','ESH',null).save()
    def pais194 = new Pais('Samoa', 'WS','WSM',685).save()
    def pais195 = new Pais('Samoa Americana', 'AS','ASM',1684).save()
    def pais196 = new Pais('San Bartolomé', 'BL','BLM',590).save()
    def pais197 = new Pais('San Cristóbal y Nieves', 'KN','KNA',1869).save()
    def pais198 = new Pais('San Marino', 'SM','SMR',378).save()
    def pais199 = new Pais('San Martín (Francia)', 'MF','MAF',1599).save()
    def pais200 = new Pais('San Pedro y Miquelón', 'PM','SPM',508).save()
    def pais201 = new Pais('San Vicente y las Granadinas', 'VC','VCT',1784).save()
    def pais202 = new Pais('Santa Elena', 'SH','SHN',290).save()
    def pais203 = new Pais('Santa Lucía', 'LC','LCA',1758).save()
    def pais204 = new Pais('Santo Tomé y Príncipe', 'ST','STP',239).save()
    def pais205 = new Pais('Senegal', 'SN','SEN',221).save()
    def pais206 = new Pais('Serbia', 'RS','SRB',381).save()
    def pais207 = new Pais('Seychelles', 'SC','SYC',248).save()
    def pais208 = new Pais('Sierra Leona', 'SL','SLE',232).save()
    def pais209 = new Pais('Singapur', 'SG','SGP',65).save()
    def pais210 = new Pais('Siria', 'SY','SYR',963).save()
    def pais211 = new Pais('Somalia', 'SO','SOM',252).save()
    def pais212 = new Pais('Sri lanka', 'LK','LKA',94).save()
    def pais213 = new Pais('Sudáfrica', 'ZA','ZAF',27).save()
    def pais214 = new Pais('Sudán', 'SD','SDN',249).save()
    def pais215 = new Pais('Suecia', 'SE','SWE',46).save()
    def pais216 = new Pais('Suiza', 'CH','CHE',41).save()
    def pais217 = new Pais('Surinám', 'SR','SUR',597).save()
    def pais218 = new Pais('Svalbard y Jan Mayen', 'SJ','SJM',null).save()
    def pais219 = new Pais('Swazilandia', 'SZ','SWZ',268).save()
    def pais220 = new Pais('Tadjikistán', 'TJ','TJK',992).save()
    def pais221 = new Pais('Tailandia', 'TH','THA',66).save()
    def pais222 = new Pais('Taiwán', 'TW','TWN',886).save()
    def pais223 = new Pais('Tanzania', 'TZ','TZA',255).save()
    def pais224 = new Pais('Territorio Británico del Océano Índico', 'IO','IOT',null).save()
    def pais225 = new Pais('Territorios Australes y Antárticas Franceses', 'TF','ATF',null).save()
    def pais226 = new Pais('Timor Oriental', 'TL','TLS',670).save()
    def pais227 = new Pais('Togo', 'TG','TGO',228).save()
    def pais228 = new Pais('Tokelau', 'TK','TKL',690).save()
    def pais229 = new Pais('Tonga', 'TO','TON',676).save()
    def pais230 = new Pais('Trinidad y Tobago', 'TT','TTO',1868).save()
    def pais231 = new Pais('Tunez', 'TN','TUN',216).save()
    def pais232 = new Pais('Turkmenistán', 'TM','TKM',993).save()
    def pais233 = new Pais('Turquía', 'TR','TUR',90).save()
    def pais234 = new Pais('Tuvalu', 'TV','TUV',688).save()
    def pais235 = new Pais('Ucrania', 'UA','UKR',380).save()
    def pais236 = new Pais('Uganda', 'UG','UGA',256).save()
    def pais237 = new Pais('Uruguay', 'UY','URY',598).save()
    def pais238 = new Pais('Uzbekistán', 'UZ','UZB',998).save()
    def pais239 = new Pais('Vanuatu', 'VU','VUT',678).save()
    def pais240 = new Pais('Venezuela', 'VE','VEN',58).save()
    def pais241 = new Pais('Vietnam', 'VN','VNM',84).save()
    def pais242 = new Pais('Wallis y Futuna', 'WF','WLF',681).save()
    def pais243 = new Pais('Yemen', 'YE','YEM',967).save()
    def pais244 = new Pais('Yibuti', 'DJ','DJI',253).save()
    def pais245 = new Pais('Zambia', 'ZM','ZMB',260).save()
    def pais246 = new Pais('Zimbabue', 'ZW','ZWE',263).save()

    Curso c1=new Curso('C000', 'SERVICIO PROFESIONAL DE CARRERA', 'SERVICIO PROFESIONAL DE CARRERA', 'Analizar los referentes teóricos y normativos que sustentan el plan y programas de estudios de Educación Básica, para fortalecer la práctica docente en el aula.','/').save()
    Curso c2=new Curso('C001', 'TEORÍA Y NORMATIVIDAD DE LA EDUCACIÓN BÁSICA EN MÉXICO', 'TEORÍA Y NORMATIVIDAD DE LA EDUCACIÓN BÁSICA EN MÉXICO', 'Analizar los referentes teóricos y normativos que sustentan el plan y programas de estudios de Educación Básica, para fortalecer la práctica docente en el aula.','/').save()
    Curso c3=new Curso('C002', 'ADAPTACIÓN CURRICULAR EN EL AULA', 'ADAPTACIÓN CURRICULAR EN EL AULA', 'Identificar las características individuales de los alumnos con necesidades educativas especiales para realizar la modificación de contenidos, estrategias de enseñanza y métodos de evaluación, para favorecer la inclusión educativa.','/').save()
    Curso c4=new Curso('C003', 'LIDERAZGO EFECTIVO EN LA ESCUELA', 'LIDERAZGO EFECTIVO EN LA ESCUELA', 'Identificar el liderazgo efectivo para crear ambientes favorables de trabajo en equipo y lograr el funcionamiento eficaz del centro escolar.','/').save()
    Curso c5=new Curso('C004', 'SOLUCIÓN DE CONFLICTOS EN EL AULA', 'SOLUCIÓN DE CONFLICTOS EN EL AULA', 'Desarrollar habilidades sociales e  implementar estrategias que permitan la solución de conflictos para lograr un clima de convivencia sano y pacífico en el aula.','/').save()
    Curso c6=new Curso('C005', 'ALTA DIRECCIÓN EN INSTITUCIONES EDUCATIVAS', 'ALTA DIRECCIÓN EN INSTITUCIONES EDUCATIVAS', 'Desarrollar competencias de alta dirección, para aplicarlas en la administración y gestión de instituciones educativas.','/').save()
    Curso c7=new Curso('C006', 'LA ESCUELA COMO ORGANIZACIÓN INTELIGENTE', 'LA ESCUELA COMO ORGANIZACIÓN INTELIGENTE', 'Identificar y analizar las características de las organizaciones inteligentes para diseñar estrategias de gestión escolar, que conviertan a la escuela en una organización que aprende.','/').save()
    Curso c8=new Curso('C007', 'GESTIÓN DEL TALENTO HUMANO EN INSTITUCIONES EDUCATIVAS', 'GESTIÓN DEL TALENTO HUMANO EN INSTITUCIONES EDUCATIVAS', 'Identificar el talento humano de los miembros de la comunidad escolar para gestionarlo en beneficio de la comunidad escolar.','/').save()
    Curso c9=new Curso('C008', 'FUNDAMENTOS DIDÁCTICOS PARA EL PROCESO ENSEÑANZA APRENDIZAJE EN EL AULA', 'FUNDAMENTOS DIDÁCTICOS PARA EL PROCESO ENSEÑANZA APRENDIZAJE EN EL AULA', 'Analizar los referentes teóricos de los enfoques didácticos que sustentan la práctica docente en el aula, para diferenciar las características e implicaciones de cada uno de ellos en el proceso enseñanza-aprendizaje y mejorar su práctica docente.','/').save()
    Curso c10=new Curso('C009', 'INSTRUMENTACIÓN DIDÁCTICA EN EL AULA', 'INSTRUMENTACIÓN DIDÁCTICA EN EL AULA', 'Diseñar un plan de acción coherente y sistematizado para orientar el desarrollo del proceso enseñanza-aprendizaje con base en los contenidos educativos; los propósitos e intenciones y las necesidades de aprendizaje de los alumnos.','/').save()
    Curso c11=new Curso('C010', 'INTERACCIÓN SOCIAL EN EL AULA Y DINÁMICA DE GRUPOS', 'INTERACCIÓN SOCIAL EN EL AULA Y DINÁMICA DE GRUPOS', 'Identificar los factores que intervienen en la interacción social en el aula,  para explicar su impacto en la dinámica del grupo y diseñar estrategias de intervención pedagógica que favorezcan relaciones y ambientes de aprendizaje favorables.','/').save()
    Curso c12=new Curso('C011', 'TÉCNICAS GRUPALES PARA EL AULA', 'TÉCNICAS GRUPALES PARA EL AUL', 'Identificar la clasificación, las características y el objetivo de diversas  técnicas grupales, para seleccionarlas y aplicarlas en el aula en función de los contenido, características y necesidades de aprendizaje del  grupo.','/').save()
    Curso c13=new Curso('C012', 'LIDERAZGO DOCENTE EN EL AULA', 'LIDERAZGO DOCENTE EN EL AULA', 'Identificar las competencias de liderazgo para desarrollarlas en su intervención pedagógica en el aula.','/').save()
    Curso c14=new Curso('C013', 'DESARROLLO DE HABILIDADES SOCIOAFECTIVAS Y ÉTICAS EN EL AULA', 'DESARROLLO DE HABILIDADES SOCIOAFECTIVAS Y ÉTICAS EN EL AULA', 'Identificar e implementar estrategias de trabajo colaborativo, que permitan el desarrollo de habilidades socioafectivas y éticas en los alumnos, para propiciar la convivencia armónica en el contexto escolar.','/').save()
    Curso c15=new Curso('C014', 'DIVERSIDAD EN EL AULA: INTEGRACIÓN E INCLUSIÓN EDUCATIVA', 'DIVERSIDAD EN EL AULA: INTEGRACIÓN E INCLUSIÓN EDUCATIVA', 'Reconocer las estrategias de evaluación psicopedagógica para lograr la integración e inclusión educativa en la atención de la diversidad del aprendizaje en el aula.','/').save()
    Curso c16=new Curso('C015', 'PLANEACIÓN DIDÁCTICA EN EL AULA', 'PLANEACIÓN DIDÁCTICA EN EL AULA', 'Identificar los elementos que integran la planeación de contenidos del aprendizaje, para diseñar las secuencias didácticas que favorezcan la organización del trabajo en el aula.','/').save()
    Curso c17=new Curso('C016', 'ESTILOS Y RITMO DE APRENDIZAJE: SU IMPORTANCIA EN LA INTERVENCIÓN DIDÁCTICA', 'ESTILOS Y RITMO DE APRENDIZAJE: SU IMPORTANCIA EN LA INTERVENCIÓN DIDÁCTICA', 'Reconocer los estilos y ritmo de aprendizaje de los alumnos, para diseñar estrategias didácticas que le permitan alcanzar los objetivos propuestos en el aula.','/').save()
    Curso c18=new Curso('C017', 'INNOVACIÓN PEDAGÓGICA EN EL AULA', 'INNOVACIÓN PEDAGÓGICA EN EL AULA', 'Distinguir los principales modelos de enseñanza, para establecer estrategias pedagógicas  innovadoras  en el aula.','/').save()
    Curso c19=new Curso('C018', 'EVALUACIÓN DEL APRENDIZAJE EN EL AULA', 'EVALUACIÓN DEL APRENDIZAJE EN EL AULA', 'Elaborar instrumentos de evaluación del aprendizaje, que le permitan identificar el desempeño de los alumnos para mejorar el aprovechamiento escolar en el aula.','/').save()
    Curso c20=new Curso('C019', 'CREACIÓN DE AMBIENTES COLABORATIVOS DE APRENDIZAJE', 'CREACIÓN DE AMBIENTES COLABORATIVOS DE APRENDIZAJE', 'Propiciar la creación de ambientes de aprendizaje a través de técnicas de trabajo colaborativo en el aula, para el logro de aprendizajes esperados.','/').save()
    Curso c21=new Curso('C020', 'DISEÑO DE OBJETOS DE APRENDIZAJE', 'DISEÑO DE OBJETOS DE APRENDIZAJE', 'Diseñar objetos de aprendizaje orientados a la realización de proyectos educativos para lograr una práctica pedagógica con base en las necesidades educativas.','/').save()
    Curso c22=new Curso('C021', 'LA LECTURA COMO ESTRATEGIA DE APRENDIZAJE', 'LA LECTURA COMO ESTRATEGIA DE APRENDIZAJE', 'Analizar la lectura como una estrategia de aprendizaje para favorecer la transversalidad de los contenidos educativos.','/').save()
    Curso c23=new Curso('C022', 'USO DE LAS TIC EN LA FORMACIÓN DOCENTE', 'USO DE LAS TIC EN LA FORMACIÓN DOCENTE', 'Desarrollar competencias digitales en  la selección y uso de información,  para promover la actualización permanente y mejorar la práctica docente.','/').save()
    Curso c24=new Curso('C023', 'RESPONSABILIDAD ÉTICA EN EL AULA', 'RESPONSABILIDAD ÉTICA EN EL AULA', 'Identificar los conocimientos éticos y normativos de la práctica docente, para propiciar un ambiente de equidad, garantizando la integridad, respeto y seguridad de los alumnos en la escuela.','/').save()
    Curso c25=new Curso('C024', 'LA PRÁCTICA DOCENTE Y EL CONTEXTO SOCIOCULTURAL', 'LA PRÁCTICA DOCENTE Y EL CONTEXTO SOCIOCULTURAL', 'Analizar el impacto del contexto social, cultural y familiar de los alumnos en su práctica docente, para diseñar acciones de intervención con la comunidad escolar.','/').save()
    Curso c26=new Curso('C025', 'LA PRÁCTICA DOCENTE Y LOS PROBLEMAS SOCIALES', 'LA PRÁCTICA DOCENTE Y LOS PROBLEMAS SOCIALES', 'Distinguir los diferentes problemas sociales que afectan a los alumnos, a fin de implementar estrategias docentes para el logro de los objetivos de aprendizaje.','/').save()
    Curso c27=new Curso('C026', 'ESTRATEGIAS DE INTERVENCIÓN EN LA ENSEÑANZA DE LAS MATEMÁTICAS', 'ESTRATEGIAS DE INTERVENCIÓN EN LA ENSEÑANZA DE LAS MATEMÁTICAS', 'Explicar los factores que intervienen en la enseñanza de las matemáticas,  para diseñar estrategias didácticas que favorezcan el aprendizaje en el aula.','/').save()
    Curso c28=new Curso('C027', 'INCLUSIÓN EDUCATIVA EN EL CONTEXTO ESCOLAR', 'INCLUSIÓN EDUCATIVA EN EL CONTEXTO ESCOLAR', 'Desarrollar competencias que le permitan intervenir acertadamente en la resolución de conflictos, generación de espacios y ambientes favorables, para la inclusión educativa y la seguridad de los integrantes del contexto escolar.','/').save()
    Curso c29=new Curso('C028', 'CREACIÓN DE REDES DE APRENDIZAJE', 'CREACIÓN DE REDES DE APRENDIZAJE', 'Reconocer las características sociales y culturales  del contexto escolar, para crear redes de aprendizaje y de trabajo con la comunidad académica, con la finalidad de  fortalecer la tarea educativa.','/').save()
    Curso c30=new Curso('C029', 'GESTIÓN ESCOLAR', 'GESTIÓN ESCOLAR', 'Diseñar estrategias de gestión escolar, para fortalecer la mejora de las prácticas docentes y el logro de los objetivos de aprendizaje.','/').save()

        new EntidadFederativa(01,'Ags.', 'Aguascalientes').save()
        new EntidadFederativa(02,'BC', 'Baja California').save()
        new EntidadFederativa(03,'BCS', 'Baja California Sur').save()
        new EntidadFederativa(04,'Camp.', 'Campeche').save()
        new EntidadFederativa(05,'Coah.', 'Coahuila de Zaragoza').save()
        new EntidadFederativa(06,'Col.', 'Colima').save()
        new EntidadFederativa(07,'Chis.', 'Chiapas').save()
        new EntidadFederativa(08,'Chih.', 'Chihuahua').save()
        new EntidadFederativa(09,'DF', 'Distrito Federal').save()
        new EntidadFederativa(10,'Dgo.', 'Durango').save()
        new EntidadFederativa(11,'Gto.', 'Guanajuato').save()
        new EntidadFederativa(12,'Gro.', 'Guerrero').save()
        new EntidadFederativa(13,'Hgo.', 'Hidalgo').save()
        new EntidadFederativa(14,'Jal.', 'Jalisco').save()
        new EntidadFederativa(15,'Mex.', 'México').save()
        new EntidadFederativa(16,'Mich.', 'Michoacán de Ocampo').save()
        new EntidadFederativa(17,'Mor.', 'Morelos').save()
        new EntidadFederativa(18,'Nay.', 'Nayarit').save()
        new EntidadFederativa(19,'NL', 'Nuevo León').save()
        new EntidadFederativa(20,'Oax.', 'Oaxaca').save()
        new EntidadFederativa(21,'Pue.', 'Puebla').save()
        new EntidadFederativa(22,'Qro.', 'Querétaro').save()
        new EntidadFederativa(23,'Q. Roo', 'Quintana Roo').save()
        new EntidadFederativa(24,'SLP', 'San Luis Potosí').save()
        new EntidadFederativa(25,'Sin.', 'Sinaloa').save()
        new EntidadFederativa(26,'Son.', 'Sonora').save()
        new EntidadFederativa(27,'Tab.', 'Tabasco').save()
        new EntidadFederativa(28,'Tamps.', 'Tamaulipas').save()
        new EntidadFederativa(29,'Tlax.', 'Tlaxcala').save()
        new EntidadFederativa(30,'Ver.', 'Veracruz de Ignacio de la Llave').save()
        new EntidadFederativa(31,'Yuc.', 'Yucatán').save()
        new EntidadFederativa(32,'Zac.', 'Zacatecas').save()

      //def curso = new Curso('SCRUM', 'Metodologias Agiles').save()
      //def modulo = new Modulo('AA', curso).save()
      
      //curso.flush()
      
      UserRole.withSession {
         it.flush()
         it.clear()
      }

      assert User.count() == 3
      assert Role.count() == 3
      assert UserRole.count() == 4
    }
    def destroy = {
    }
}
